 # The native communication protocol.
{ 
    name = libpipewire-module-protocol-native
    args = {
        # List of server Unix sockets, and optionally permissions
        sockets = [ { name = "pipewire-0" }, { name = "pipewire-0-manager" }, { name = "/tmp/pipewire-shared.socket", mode = "0777" } ]
    }
}

